import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "primeflex/primeflex.css";
import "./dashboard.css";

import { Open_Sans } from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const openSans = Open_Sans({
  display: 'swap',
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={
        { background: "#f3f2fc", padding: '0' }
      } className={ openSans.className }>
        <AntdRegistry>
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
